In [ ]:
import numpy as np
x = int(input())
a1 = np.zeros(x, int)

for i in range(x) :
    a1[i] = int(input())
print('Original Array:', a1)
a2 = np.zeros(x+1, int)

for i in range(x) :
    a2[i] = a1[i]
y = int(input())
a2[x] = y
print('Resized Array:', a2)

3
5
8
2
9
Original Array: [5 8 2]
Resized Array: [5 8 2 9]


In [ ]:
import numpy as np
x = int(input())
a1 = np.zeros(x, int)

for i in range(x) :
    a1[i] = int(input())
print('Original Array:', a1)

for i in range(x) :
    if a1[i] > 0 :
        a1[i] = 1
    else :
        a1[i] = 0
print('After modifying:', a1)

3
-4
0
2
Original Array: [-4  0  2]
After modifying: [0 0 1]


In [ ]:
import numpy as np

def reverseArray(x) :
    i, j = 0, x.size-1
    while i < j :
        x[i], x[j] = x[j], x[i]
        i, j = i+1, j-1
    return x

arr1 = np.array([10, 12, 20, 5, 7])
arr1 = reverseArray(arr1)
print(arr1)

arr2 = np.array([4, 2, 6, 5])
arr2 = reverseArray(arr2)
print(arr2)

[ 7  5 20 12 10]
[5 6 2 4]


In [ ]:
import numpy as np

def printPairs(arr, sum) :
    flag = False
    for i in range(arr.size) :
        for j in range(i+1, arr.size) :
            if arr[i]+arr[j] == sum :
                flag = True
                print(f'{arr[i]}, {arr[j]}')
    if flag == False :
        print('No Pair Found')

arr1 = np.array([7,8,10,5,3,4,2])
printPairs(arr1, 15)

arr2 = np.array([2,-3,1,9,4,5])
printPairs(arr2, 6)

arr3 = np.array([5, 9, 7, 6, 10])
printPairs(arr3, 18)

7, 8
10, 5
2, 4
-3, 9
1, 5
No Pair Found


In [ ]:
import numpy as np
vec1 = np.array([1,2,3,7])
vec2 = np.array([4,5,6,9])
dot, x = 0, vec1.size

for i in range(x) :
    dot += vec1[i]*vec2[i]
print('Dot Product:', dot)

if dot%2 == 0 :
    for i in range(0, x, 2) :
        vec1[i], vec2[i] = vec2[i], vec1[i]

else :
    for i in range(1, x, 2) :
        vec1[i], vec2[i] = vec2[i], vec1[i]

print(f'After Swapping: \n{vec1}\n{vec2}')

Dot Product: 95
After Swapping: 
[1 5 3 9]
[4 2 6 7]


In [ ]:
import numpy as np
n = int(input())
arr = np.zeros(n, int)

for i in range(n) :
    arr[i] = int(input())
print('Original Array:', arr)

for i in range(n-1) :
    min = i
    for j in range(i+1, n) :
        if arr[j] < arr[min] :
            min = j
    arr[i], arr[min] = arr[min], arr[i]
print('Sorted Array:', arr)

6
3
6
1
2
8
5
Original Array: [3 6 1 2 8 5]
Sorted Array: [1 2 3 5 6 8]


In [ ]:
import numpy as np

def flatten(x) :
    row = x.shape[0]
    col = x.shape[1]
    y = np.zeros(x.size, int)
    count = 0
    for i in range(row) :
        for j in range(col) :
            y[count] = x[i][j]
            count += 1
    return y

arr1 = np.array( [ [1, 2, 3], [3, 4, 5] ] )
arr2 = flatten(arr1)
print(arr2)

[1 2 3 3 4 5]


In [ ]:
import numpy as np
A = np.array([  [1, 0, 0],
                [0, 1, 0],
                [0, 0, 1] ])

row = A.shape[0]
col = A.shape[1]
flag = False

for i in range(row) :
    for j in range(col) :
        if i == j :
            if A[i][j] == 1 :
                flag = True
            else :
                flag = False
                break
        else :
            if A[i][j] == 0 :
                flag = True
            else :
                flag = False
                break

if flag == True :
    print('Identity Matrix')
else :
    print('Not an Identity Matrix')

Identity Matrix


In [ ]:
import numpy as np
A = np.array([  [1,  5,  12,  1],
                [2,  -4,  6,  7],
                [3,  8,  5,  9],
                [3,  5,  23,  -6] ])

row = A.shape[0]
col = A.shape[1]
d1, d2 = 0, 0

for i in range(row) :
    for j in range(col) :
        if i == j :
            d1 += A[i][j]

for i in range(row) :
    j = col
    while j >= 0 :
        if i+j == row-1 :
            d2 += A[i][j]
        j -= 1
print(abs(d1-d2))

22


In [ ]:
import numpy as np
A = np.array([[1,2,3,4],
              [1,4,9,16]])


row = A.shape[0]
col = A.shape[1]
At = np.zeros((col, row), int)

for i in range(row) :
    for j in range(col) :
        At[j][i] = A[i][j]
print(At)

[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]


In [ ]:
import numpy as np
A = np.array([[1,2,3,4],
              [1,4,9,16]])

row = A.shape[0]
col = A.shape[1]
At = np.zeros((col, row), int)

for i in range(row) :
    for j in range(col) :
        At[j][i] = A[i][j]

gram = np.zeros((col, col), int)
sum = 0

for i in range(col) :
    for j in range(col) :
        for k in range(row) :
            gram[i][j] += At[i][k]*A[k][j]
print(gram)

[[  2   6  12  20]
 [  6  20  42  72]
 [ 12  42  90 156]
 [ 20  72 156 272]]


In [18]:
import numpy as np
A = np.array([[4,1,2],
              [9,3,7]])

row = A.shape[0]
col = A.shape[1]
ab = abs(row-col)
rem = ab%row
sum = 0

for i in range(col) :
    sum += A[rem][i]
avg = round(sum/col, 2)
B = np.zeros((row, col), float)
for i in range(row) :
    for j in range(col) :
        B[i][j] = A[i][j]*avg
print(B)

[[27.  13.5]
 [ 4.5 22.5]]
